# Generated by Django 3.1 on 2021-05-23 17:36

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='title')),
                ('text', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='DailyEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='events', verbose_name='img')),
                ('title', models.CharField(max_length=400, verbose_name='title')),
                ('subtitle', models.CharField(max_length=1000, verbose_name='subtitle')),
                ('text', models.CharField(max_length=1000, verbose_name='text')),
                ('data', models.CharField(max_length=1000, verbose_name='text_data')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
            ],
            options={
                'verbose_name': 'Daily Events',
                'verbose_name_plural': 'Daily Events',
            },
        ),
        migrations.CreateModel(
            name='MenuCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Menu Categories',
                'verbose_name_plural': 'MenuCategories',
            },
        ),
        migrations.CreateModel(
            name='OpenTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=300, verbose_name='open time')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
            ],
            options={
                'verbose_name': 'Open Time',
                'verbose_name_plural': 'Open Time',
            },
        ),
        migrations.CreateModel(
            name='OurLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Our Location')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
            ],
            options={
                'verbose_name': 'Our Location',
                'verbose_name_plural': 'Our Location',
            },
        ),
        migrations.CreateModel(
            name='RESERVATIONS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=3000, verbose_name='text')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
            ],
            options={
                'verbose_name': 'RESERVATIONS',
                'verbose_name_plural': 'RESERVATIONS',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='slider', verbose_name='img')),
                ('name', models.CharField(max_length=3000, verbose_name='name img')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Slider',
            },
        ),
        migrations.CreateModel(
            name='SportEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='events', verbose_name='img')),
                ('title', models.CharField(max_length=400, verbose_name='title')),
                ('text', models.CharField(max_length=1000, verbose_name='text')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
            ],
            options={
                'verbose_name': 'Sport Events',
                'verbose_name_plural': 'Sport Events',
            },
        ),
        migrations.CreateModel(
            name='TableReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=300, verbose_name='phone')),
                ('email', models.EmailField(max_length=254)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
            ],
            options={
                'verbose_name': 'Table Reservation',
                'verbose_name_plural': 'Table Reservation',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='categories', verbose_name='img')),
                ('title', models.CharField(max_length=400, verbose_name='title')),
                ('text', models.CharField(max_length=1000, verbose_name='text')),
                ('price', models.IntegerField(verbose_name='price')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('menu_categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='webapp.menucategories', verbose_name='menu categories')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menu',
            },
        ),
    ]
