# Generated by Django 3.1 on 2021-05-23 11:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='subtitle',
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
